Quick Start draft 0.0.1
opendatahub-io/distributed-workloads pull request #1
Opened 2023-01-26 15:36 UTC by MichaelClifford

## Description
First Draft of a quick start guide to using the codeflare stack with open data hub.

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-01-26 15:37 UTC, MichaelClifford commented
cc @accorvin @Maxusmusti

2023-01-26 16:48 UTC, accorvin commented
@MichaelClifford can you add a blurb in the README linking to this file just so it's more obvious?

2023-01-26 18:27 UTC, Maxusmusti requested changes
Looks good, just a few details that may be worth mentioning

2023-01-26 18:27 UTC, Maxusmusti commented on Quick-Start.md
> +_Note_: Instascale is intended for public cloud environments were it is possible to provision additional hardware on demand. If you are working with an on-prem cluster, you can **skip this step**.
"were" -> "where"

2023-01-26 18:27 UTC, Maxusmusti commented on Quick-Start.md
> +oc apply -f custom-nb-images/imagestream.yaml
Should there be a `-n namespace` on this command as well?

2023-01-26 18:27 UTC, Maxusmusti commented on Quick-Start.md
> +    instascale=True,
The `machine_types` and `instascale=True` both require instascale on the cluster. Also note that the first machine_type is currently  for head node, and the second is for worker nodes. Finally, for each machine type a user wants to be able to scale, the cluster has to have a machine_set template available (can be done easily by copying the yaml of an existing machineset with zero replicas, and just changing the cpu/gpu/memory annotations at the top, and the `instanceType` field. That will add the machine type to instascale's "market place"

2023-01-26 18:27 UTC, Maxusmusti commented on Quick-Start.md
> +Fist we will use [Helm](https://helm.sh/) to install MCAD.
I also believe the KubeRay operator install requires at least Helm 3(?), which is why I had that check/upgrade in the prep script

2023-01-26 18:47 UTC, MichaelClifford commented on Quick-Start.md
> +oc apply -f custom-nb-images/imagestream.yaml
I'm assuming they are in their open data hub namespace, what would be the default namespace we would add here that would general enough to use? 

or should it be like `-n <your open data hub namespace>`?

2023-01-26 18:58 UTC, MichaelClifford commented on Quick-Start.md
> +    instascale=True,
:+1:  I'll add some comments about machine types and assumption on instascale. 

But the machine_set sounds a little involved. Is there an existing yaml as part of the artifacts that we can point to for this part?

2023-01-26 19:11 UTC, MichaelClifford commented on Quick-Start.md
> +oc apply -f custom-nb-images/imagestream.yaml
yeah, in ODH its just the name of whatever you called the namespace you installed ODH in. 

You think we should leave it as is or add the `-n <name>`?

2023-01-26 19:12 UTC, Maxusmusti commented on Quick-Start.md
> +    instascale=True,
The issue with a template is that the issue with that there is a section that will always be unique to a specific cluster:
```
securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - prepfullinstall-6mzcr-worker-sg
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/prepfullinstall-6mzcr
              value: owned
          deviceIndex: 0
          ami:
            id: ami-026e5701f495c94a2
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - prepfullinstall-6mzcr-private-us-east-2a
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: prepfullinstall-6mzcr-worker-profile
```

2023-01-26 19:15 UTC, Maxusmusti commented on Quick-Start.md
> +    instascale=True,
I think there are two potential solutions: add the ability to add/configure machinetype options through the sdk (generate and apply a zero-replica machineset template in the backend), or give instascale the ability to make these machinesets possibly, which may be more complicated to implement, but possibly more streamlined for the user. Only thing is permissions on who gets to decide which machinetypes are allowed and for who. I'll add this to the monday agenda as well.

2023-01-26 19:27 UTC, Maxusmusti commented on Quick-Start.md
> +oc apply -f custom-nb-images/imagestream.yaml
I think the `-n <your open data hub namespace>` is good, just to be safe

2023-01-26 21:40 UTC, ashishkamra commented on Quick-Start.md
> +_Note_: Instascale is intended for public cloud environments where it is possible to provision additional hardware on demand. If you are working with an on-prem cluster, you can **skip this step**.
".. provision additional resources on demand."

I recommend rephrase the last sentence as "You can skip installing Instascale if you do not anticipate dynamically scaling up or down your OpenShift cluster". 
on-prem is a broad term and users may have virtualized on-prem environments where Instascale might be useful.

2023-01-26 21:51 UTC, ashishkamra commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
Can we have any other example of a distributed model training? I think showing that we can train an MNIST model using this stack is little underwhelming. Showcasing training of a LLM like BERT will be great.

2023-01-26 21:55 UTC, ashishkamra commented on Quick-Start.md
> +These distributed functions can be of arbitrary complexity including model training. For a more complex example take a look at `codeflare-sdk/demo-notebooks/interactive/hf_interactive.ipynb` where we
OK, so I suggest make the fine tuning of a pre-trained huggingface model as the working example in this guide instead of MNIST.

2023-01-26 22:01 UTC, MichaelClifford commented on Quick-Start.md
> +_Note_: Instascale is intended for public cloud environments where it is possible to provision additional hardware on demand. If you are working with an on-prem cluster, you can **skip this step**.
:+1: will do

2023-01-26 22:16 UTC, MichaelClifford commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
I agree that MNIST is not the most exciting, but it is was what we demoed for the torchx job submission workflow, and we have the script for it. We can change this to something else, but we'd have to develop some net new code to do so. 

The huggingface notebook demo below is part of the interactive workflow, so its a bit different than the mnist job submission approach and can't just replace it directly. My goal here was to walk through both of the ways that someone can interact with the stack: job submission and interactive.  But maybe that's too much for this quick start guide here. 

Here are a couple of options

1) Remove the mnist demo and the `torchx` submission bit, just focus on the interactive huggingface demo.

2) Convert the huggingface demo into a python script and show the same model training use case from both workflow styles.

@ashishkamra let me know what you think. :smile:

2023-01-27 00:50 UTC, accorvin commented on Quick-Start.md
> +This quick start guide is intended to walk existing Open Data Hub users through installation of the CodeFlare Stack and an initial demo using the CodeFlare-SDK from within a JupyterHub Environment. T
Rather than “JupyterHub” we should say “Jupyter notebook”

2023-01-27 00:51 UTC, accorvin commented on Quick-Start.md
> +Fist we will use [Helm](https://helm.sh/) to install MCAD.(Make sure you have Helm 3 or above).
We should mention this prerequisite in the prerequisites section above.

2023-01-27 00:55 UTC, accorvin commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
“Demo notebook we cloned early” <— “early” should be “earlier”

2023-01-27 00:57 UTC, accorvin commented on Quick-Start.md
> +And with that you have gotten started using the CodeFlare stack alongside your Open Data Hub Deployment to add distributed workflows and batch computing to your machine learning platform.
This content doesn’t feel aligned with the “next steps” heading to me. Maybe we can link to more advanced demos, more documentation, things like that?

2023-01-27 06:56 UTC, Maxusmusti commented
Should we also mention that use of GPUs requires the NFD/GPU operators to be installed, or should that just be assumed as a given or basic OpenShift knowledge? May be worth mentioning just in case of the scenario where they start with a cloud-based cluster with no GPUs initially (so never bothered to install gpu operator) and are scaling up?

2023-01-27 14:44 UTC, accorvin commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
IMO we should keep this quick start concise. I know personally when I open a quick start, if there are a ton of steps, I quickly get deterred and look at other options. I would vote to include only a small amount of code example and link to further/more advanced examples in the "next steps" section.

2023-01-27 14:58 UTC, MichaelClifford commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
@accorvin Are you suggesting leaving it as is, or removing the MNIST part all together? Or a 3rd option. I'm also a fan of keeping things concise, and this doc is starting to feel like its growing a little outside the bounds of a "quick start"  so any recommendation for simplifying are welcome :smile:

2023-01-27 15:10 UTC, accorvin commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
@MichaelClifford I think I'd vote to keep the "submit your first job" section more or less as is and then remove the "Interactive Session" section (we already have an item in "next steps" that would instruct someone on how to do this). Then specifically call out some of the more advanced options that we have under the "next steps" section.

2023-01-30 00:39 UTC, ashishkamra commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
Since we are trying to get something out sooner than later, it is fine to publish with MNIST to start with. Meanwhile, I suggest working on showcasing training or fine-tuning a model from huggingface worthy of distributed training using this stack 🙂.

2023-01-30 14:32 UTC, MichaelClifford commented on Quick-Start.md
> +We will rely on the demo code we cloned early to train an mnist model. So feel free to open `codeflare-sdk/demo-notebooks/batch-job/batch_mnist.ipynb` to follow along instead. You can upload the repo
Sounds Good @ashishkamra. 

So I've addressed the comments above by taking out the section on "Interactive Session" and just leaving the MNIST section for now, with the caveat that we will work on putting together a more sophisticated demo as one of our next issues to replace MNIST. 

Thanks for all your comments :) Let me know if there is anything else you'd like me to change here.

2023-01-30 17:26 UTC, anishasthana commented on Quick-Start.md
> +The CodeFlare-SDK was built to make managing distributed compute infrastructure in the cloud easy and intuitive for Data Scientists. However, that means there needs to be some cloud infrastructure on
```suggestion
The CodeFlare-SDK was built to make managing distributed compute infrastructure in the cloud easy and intuitive for Data Scientists. However, that means there needs to be some cloud infrastructure on the backend for users to get the benefit of using the SDK. Currently, we support the CodeFlare Stack, which consists of the Open Source projects, [MCAD](https://github.com/project-codeflare/multi-cluster-app-dispatcher), [Instascale](https://github.com/project-codeflare/instascale), [Ray](https://www.ray.io/), and [Pytorch](https://pytorch.org/).
```

2023-01-30 17:26 UTC, anishasthana commented on Quick-Start.md
> +This stack integrates well with [Open Data Hub](https://opendatahub.io/), and helps to bring batch workloads, jobs and queuing to the Data Science platform.
```suggestion
This stack integrates well with [Open Data Hub](https://opendatahub.io/) and helps to bring batch workloads, jobs, and queuing to the Data Science platform. 
```

2023-01-30 17:34 UTC, Maxusmusti requested changes
I went through and tested everything out, and it all looks good! Just a few minor things I noticed along the way:

2023-01-30 17:34 UTC, Maxusmusti commented on Quick-Start.md
> +
Missing closing ")"

2023-01-30 17:34 UTC, Maxusmusti commented on Quick-Start.md
> +oc apply -f custom-nb-images/imagestream.yaml -n <your Open Data Hub namespace>
`custom-nb-images` -> `custom-nb-image`

2023-01-30 17:34 UTC, Maxusmusti commented on Quick-Start.md
> +
Mention of a cluster.down() when everything is complete?

2023-01-30 17:34 UTC, Maxusmusti commented on Quick-Start.md
> +* [Run an interactive session](https://github.com/project-codeflare/codeflare-sdk/tree/main/demo-notebooks/interactive)
Should there be a little more explanation about the option to work interactively (maybe like a single line or bullet point explaining the option), or should we add an additional README in that folder?

2023-01-30 17:34 UTC, Maxusmusti commented on Quick-Start.md
> +The CodeFlare-SDK was built to make managing distributed compute infrastructure in the cloud easy and intuitive for Data Scientists. However, that means there needs to be some cloud infrastructure on
Is there a reason we are going with just "in the cloud" as opposed to also "on-prem" for our description? Given that it works with both baremetal clusters and cloud-based clusters (and the baremetal scenario is being tested by customers first), could this lead to any confusion, or is it best to just leave this as is?

2023-01-31 13:14 UTC, anishasthana commented on Quick-Start.md
> +* [Run an interactive session](https://github.com/project-codeflare/codeflare-sdk/tree/main/demo-notebooks/interactive)
I think there should be a README in that folder instead of adding more information here

2023-01-31 15:58 UTC, MichaelClifford commented on Quick-Start.md
> +* [Run an interactive session](https://github.com/project-codeflare/codeflare-sdk/tree/main/demo-notebooks/interactive)
yes, let's add a README in the sdk repo, not here.

2023-01-31 18:43 UTC, merged