update quickstart to reflect ODH embedded CodeFlare
opendatahub-io/distributed-workloads pull request #150
Opened 2023-10-27 22:00 UTC by KPostOffice

## Description

Update v2 QuickStart to reflect that the CFO is not intended to be installed separately from ODH anymore
Closes #149

## How Has This Been Tested?

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-10-30 08:10 UTC, sutaakar commented on Quick-Start-ODH-V2.md
> +<!-- TODO: do we still provide a notebook image? or is it just the base because the SDK is now included in the base image -->
I would guess that we shouldn't provide own image any more.
@dimakis What do you think?

2023-10-31 16:51 UTC, jbusche requested changes
I tried the install, but noticed some items not working, noted in comments

2023-10-31 17:59 UTC, sutaakar commented on Quick-Start-ODH-V2.md
> -### CodeFlare Operator
it seems that ODH doesn't contain the own CodeFlare installation yet. It should be there in next version.

2023-10-31 20:57 UTC, KPostOffice commented on Quick-Start-ODH-V2.md
> -### CodeFlare Operator
^^ it should be present in 2.3 or 2.4 I believe

2023-11-01 10:51 UTC, dimakis commented on Quick-Start-ODH-V2.md
> -### CodeFlare Operator
yes, we are in a weird state currently which is not helped by the delays. I believe release date is within the next two weeks

2023-11-01 10:52 UTC, dimakis commented on Quick-Start-ODH-V2.md
> +<!-- TODO: do we still provide a notebook image? or is it just the base because the SDK is now included in the base image -->
I feel like we should provide our own image still. If it is already there and not much maintenance is needed then we should keep it

2023-11-06 18:27 UTC, KPostOffice commented
I can go through all the manual steps, but I'm having trouble with the `make all-in-one` so I'm trying to debug it and make it more accurate to the current install path.

2023-11-06 19:50 UTC, KPostOffice commented on Quick-Start-ODH-V2.md
> -   oc delete sub codeflare-operator -n openshift-operators
`dsc` works with the latest release of the operator from my testing

2023-11-06 19:52 UTC, KPostOffice commented on Quick-Start-ODH-V2.md
> -   oc delete sub codeflare-operator -n openshift-operators
> But maybe once the CodeFlare operator is really installing with the datasciencecluster properly, it won't have the sub and csv that'll need to be cleaned up...?

Yeah, there won't be a codeflare csv after these changes. The controller is being managed by the ODH/OpenShift AI operator

2023-11-06 20:50 UTC, dimakis reviewed
Great work as ever @KPostOffice

2023-11-06 20:50 UTC, dimakis commented on Quick-Start.md
> +<!-- TODO: do we still provide a notebook image? or is it just the base because the SDK is now included in the base image -->
I still think we could/ should have put own image. It we retain control over it then this may be a way for us to get the latest version of codeflare sdk into users hands without the sprint lag for the other images. We may even be better able to load particular packages that we're looking at adding as the stack grows.

2023-11-06 20:50 UTC, dimakis commented on Quick-Start.md
> +    oc apply -f https://raw.githubusercontent.com/opendatahub-io/distributed-workloads/main/codeflare-dsc.yaml
I wonder about us asking a user to apply this dsc. The console asks a user who has freshly installed rhods to create a dsc. I think we should at very least mention this and point them to the components needed (cf and ray) as I've seen a number of people (myself included) end up with 2 DSCs on cluster.

2023-11-07 00:54 UTC, tedhtchang reviewed
I still don't see the Codeflare Notebook image from the ODH dashbaord
![image](https://github.com/opendatahub-io/distributed-workloads/assets/7155778/40310ce8-8362-46c0-86b3-059037950e70)

2023-11-07 01:00 UTC, tedhtchang commented on Quick-Start.md
> +make all-in-one
I tend to think this method should be listed as under development because it requires users to `git clone` the repo and requires `make` command.

2023-11-07 19:15 UTC, KPostOffice commented on Quick-Start.md
> +<!-- TODO: do we still provide a notebook image? or is it just the base because the SDK is now included in the base image -->
I'm good with that, the only question becomes whether we add it as an ImageStream that users can add independently or if it is automatically included when CodeFlare is enabled as it is now.

2023-11-07 20:22 UTC, ChristianZaccaria requested changes
Great job on this! I tested the `make all-in-one` target on OCP. It all works well except for the installation of the nfd-operator. When I try to install it I get:
```AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces```

In the `nfd-operator-subscription.yaml` file I added a spec, to target the created namespace `openshift-nfd`. Done as below, which then the installation worked for me:
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  targetNamespaces:
    - openshift-nfd
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  labels:
    operators.coreos.com/nfd.openshift-nfd: ''
  namespace: openshift-nfd
spec:
  channel: stable
  name: nfd
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  ```

2023-11-09 00:20 UTC, jbusche commented
I'm trying out the Install Steps from here in the [proposed quickstart](https://github.com/KPostOffice/distributed-workloads/blob/issue149v1/Quick-Start.md#openshift-and-open-data-hub)
And I've got the product up.  A couple of weird things, but maybe once everything settles it'll all work ok.
1.  I see the `dsc` works now, great!  I've applied it and it's loaded KubeRay, CodeFlare rc4 and an older CodeFlare notebook v0.7.0 
2. I'm running the 2_basic_jobs.ipynb guided demo and the oddest thing, it's failing with: 
```
No instances found, nothing to be done.
```
Looking at the jobtest.yaml it's showing 
```
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
```
IDK, I'm missing something, will have to look later... but I didn't expect to see mcad.ibm.com...
I've applied this [dsc](oc apply -f https://raw.githubusercontent.com/opendatahub-io/distributed-workloads/main/codeflare-dsc.yaml)
And I've cloned the latest main branch of the codeflare-sdk

2023-11-09 08:30 UTC, sutaakar commented
@jbusche I guess you are running with CodeFlare norebook, right?
That one contains old SDK, it is not clear whether the Notebook should be published. Can you try the tensorflow Notebook in meantime? That one should have latest CodeFlare SDK.

2023-11-09 17:11 UTC, jbusche commented
> @jbusche I guess you are running with CodeFlare norebook, right? That one contains old SDK, it is not clear whether the Notebook should be published. Can you try the tensorflow Notebook in meantime? That one should have latest CodeFlare SDK.

Ah, good point @sutaakar , when applied the dsc it DID pull in an older `v0.7.0` version of the notebook.  Hmmm, ok... let me see.. interesting.

2023-11-30 19:47 UTC, jbusche approved these changes
LGTM

2023-11-30 19:48 UTC, jbusche commented
Tested install on OpenShift 4.14.1 and it looks good - didn't have GPU, but the non-CPU demos looked good.  Cleanup also looked good.

2023-11-30 19:54 UTC, merged