UBI9 Ray container image
opendatahub-io/distributed-workloads pull request #177
Opened 2024-06-26 09:48 UTC by astefanutti

## Description

## How Has This Been Tested?

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-06-27 14:23 UTC, astefanutti commented on images/runtime/ray/Dockerfile
> +USER 1001
Still wonder whether we should stick to the `ray` user that is set for the upstream images?

2024-06-27 15:23 UTC, Ygnas commented on images/runtime/ray/Dockerfile
> +      authoritative-source-url="https://github.com/opendatahub-io/distrubuted-workloads" \
I think this needs to be removed.
```suggestion
      authoritative-source-url="https://github.com/opendatahub-io/distrubuted-workloads"
```

2024-06-27 16:27 UTC, KPostOffice commented on images/runtime/ray/NGC-DL-CONTAINER-LICENSE
Is this license applicable?

2024-06-27 16:28 UTC, KPostOffice commented on images/runtime/README.md
> +Sources for the ontainer images provided by Distributed Workloads for OpenShift AI.
```suggestion
Sources for the container images provided by Distributed Workloads for OpenShift AI.
```

2024-06-28 07:28 UTC, astefanutti commented on images/runtime/ray/Dockerfile
> +      authoritative-source-url="https://github.com/opendatahub-io/distrubuted-workloads" \
Good catch, updated.

2024-06-28 07:29 UTC, astefanutti commented on images/runtime/README.md
> +Sources for the ontainer images provided by Distributed Workloads for OpenShift AI.
Good catch, updated.

2024-06-28 07:30 UTC, astefanutti commented on images/runtime/ray/NGC-DL-CONTAINER-LICENSE
It is used by the Notebook images, and is provided along the Nvidia CUDA container images. I haven't check in details, but I've assumed it's applicable.

2024-06-28 08:30 UTC, Ygnas approved these changes

2024-07-01 13:55 UTC, Bobbins228 reviewed
/lgtm

2024-07-01 13:57 UTC, sutaakar commented on images/runtime/ray/Dockerfile
> +USER 1001
Thinking whether keeping `ray` user makes any difference from user point of view.
I briefly remember that someone had some issue accessing some part of Ray dashboard (I know, the description is not much specific), though I cannot reproduce it for `quay.io/rhoai/ray:2.23.0-py39-cu121`

2024-07-01 13:57 UTC, sutaakar reviewed
/lgtm

2024-07-01 13:59 UTC, Ygnas requested changes

2024-07-01 14:05 UTC, ChristianZaccaria commented on images/runtime/ray/Dockerfile
> +USER 1001
@sutaakar I might be wrong, are you referring to this issue? https://issues.redhat.com/browse/RHOAIENG-5493

2024-07-01 14:36 UTC, ChristianZaccaria reviewed
/lgtm !!

2024-07-01 15:54 UTC, astefanutti commented on images/runtime/examples/README.md
> +3. Login to the container registy, e.g., with Podman:
Good catch, thanks!

2024-07-01 15:54 UTC, astefanutti commented on images/runtime/examples/README.md
> +podman build -t {IMG} -f Dockerfile
Updated, thanks!

2024-07-01 15:56 UTC, Ygnas approved these changes

2024-07-01 16:00 UTC, astefanutti commented on images/runtime/ray/Dockerfile
> +USER 1001
RHOAIENG-5493 is rather caused by some security constraints than with the user.

Actually the `ray` user forces to lower security constraints, as the Pod cannot run with an arbitrary user. It seems from the tests we have run, that this `ray` user is only a convention introduced by the upstream image, rather than a real need, and that it works fine without it.

2024-07-02 07:21 UTC, merged