Adding basic example/walkthrough for the HPO work with raytune
opendatahub-io/distributed-workloads pull request #193
Opened 2024-07-23 12:54 UTC by ncau

## Description
Added an example/walk through for using hyperparameter optimization with raytune. This includes the required notebooks and a walk through for running them. 

## How Has This Been Tested?
Ran through the steps manually on a openshift cluster (4.14) with openshift AI (2.10) installed. 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-07-24 09:56 UTC, Srihari1192 requested changes
@ncau Seems Notebook examples are outdated,  needs to be updated with latest codeflare-sdk you can refer this demo examples for cluster configuration https://github.com/project-codeflare/codeflare-sdk/blob/main/demo-notebooks/guided-demos/1_cluster_job_client.ipynb

Also Codeflare-sdk by default available with Openshift AI in standard data science Notebook image so you can skip codeflare-sdk installation and ray

2024-08-12 07:28 UTC, sutaakar commented
@ncau Can you please check Srihari's comment and adjust your PR accordingly?

2024-08-13 07:58 UTC, ncau commented
The changes should now be in please let me know if those cover the issues

2024-08-13 08:04 UTC, astefanutti commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "    instascale=False\n",
This can be removed.

2024-08-13 08:04 UTC, astefanutti commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "    image=\"quay.io/project-codeflare/ray:latest-py39-cu118\",\n",
Please update the image with `quay.io/rhoai/ray:2.23.0-py39-cu121`.

2024-08-13 08:04 UTC, astefanutti commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "    instascale=False\n",
This can be removed.

2024-08-13 08:04 UTC, astefanutti commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "    image=\"quay.io/project-codeflare/ray:latest-py39-cu118\",\n",
Please update to `quay.io/rhoai/ray:2.23.0-py39-cu121`.

2024-08-16 12:17 UTC, ncau commented
Addressed above concerns, removed the cells that weren't needed and corrected the config images/removed the lines not needed.

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "!pip install ray[default]==2.7.0\n",
Similarly this can be removed , as `Ray` is by default available

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
> +    "!pip install ray[default]==2.7.0\n",
This can be removed , as `Ray` is by default available no need to install it explicitly

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
> +    "runtime_env = {\"pip\": [\"ipython\", \"torch\" , \"onnx\", \"ray[train]\", \"ml_metadata\" ,\"protobuf==3.20.1\"]}\n",
Similarly here as `Ray` and `ipython` is by default available can be removed

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "!pip install ray[default]==2.7.0\n",
Similarly this can be removed , as `Ray` is by default available

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "runtime_env = {\"pip\": [\"ipython\", \"torch\" , \"onnx\", \"ray[train]\", \"ml_metadata\" ,\"protobuf==3.20.1\"]}\n",
Similarly here as `Ray` and `ipython` is by default available can be removed

2024-08-19 05:45 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "runtime_env = {\"pip\": [\"ipython\", \"torch\" , \"onnx\", \"ray[train]\", \"protobuf==3.20.1\"]}\n",
Similarly here as Ray and ipython is by default available can be removed

2024-08-19 08:16 UTC, astefanutti commented on examples/hpo-raytune/README.md
> +> This example has been tested with the configurations listed in the [validation](#validation) section.
Would it be possible for you to add the details of the configurations you've used to validate that example?

Otherwise, we may want to adapt the wording here.

2024-08-19 08:16 UTC, astefanutti commented on examples/hpo-raytune/README.md
> +### Running the codeflare examples
`codeflare` -> `HPO`

2024-08-19 08:16 UTC, astefanutti commented on examples/hpo-raytune/notebook/README.md
> +# Machine Learning Model Optimization and Deployment with Ray and CodeFlare SDK
Is this README redundant with the one in the parent directory?

If there are information missing in the later, maybe they can be added and that README removed?

2024-08-20 06:06 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
> +    "    head_memory=4\n",
```suggestion
    "    head_cpus=1,\n",
    "    head_memory=4,\n",
```

2024-08-20 06:07 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "    head_memory=4\n",
```suggestion
    "    head_cpus=1,\n"",
    "    head_memory=4,\n",
```

2024-08-20 06:08 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "    head_memory=4\n",
```suggestion
    "    head_cpus=1,\n",
    "    head_memory=4,\n",
```

2024-08-20 06:15 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
> +    "cluster.up()"
```suggestion
    "cluster.up()\n",
    "cluster.wait_ready()"
```

Add cluster.wait_ready() method to wait for until cluster get ready

2024-08-20 06:15 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
> +    "cluster.up()"
```suggestion
    "cluster.up()\n",
    "cluster.wait_ready()"
```

Add cluster.wait_ready() method to wait for until cluster get ready

2024-08-20 06:15 UTC, Srihari1192 commented on examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
> +    "cluster.up()"
```suggestion
    "cluster.up()\n",
    "cluster.wait_ready()"
```

Add cluster.wait_ready() method to wait for until cluster get ready

2024-08-21 12:48 UTC, astefanutti commented
/lgtm

Could you please squash the commits once it's ready to merge?

2024-08-22 12:36 UTC, ncau commented
@astefanutti Sorry not 100% sure I've squashed correctly here or not let me know if I've fixed it here or not.

2024-08-22 12:44 UTC, astefanutti commented
@ncau It seems there are extra commits that should not be there, and also some unresolved conflicts unfortunately. Could you have a look please?

2024-08-22 13:33 UTC, astefanutti commented
@ncau thanks. There is one nit comment left on my side, otherwise LGTM.

2024-08-22 13:49 UTC, ncau commented
Should just be the one now

2024-08-22 14:00 UTC, astefanutti commented on examples/hpo-raytune/README.md
> +### Running the codeflare examples
@ncau just this one nit left.

2024-08-22 16:35 UTC, ncau commented on examples/hpo-raytune/README.md
> +### Running the codeflare examples
Fixed this and squashed the commit

2024-08-22 16:54 UTC, astefanutti commented
/lgtm

2024-08-26 07:23 UTC, Srihari1192 approved these changes

2024-08-26 07:24 UTC, astefanutti approved these changes

2024-08-26 07:27 UTC, merged