Update LLMs fine-tuning with Ray example for Llama 3.1 models
opendatahub-io/distributed-workloads pull request #204
Opened 2024-08-14 10:21 UTC by astefanutti

## Description

This PR updates the Ray fine-tuning example so it works for Llama 3.1 model series.

## How Has This Been Tested?

The changes in this PR have been successfully tested with the following models:

* meta-llama/Meta-Llama-3.1-8B (red)
* meta-llama/Meta-Llama-3.1-8B-Instruct (light blue)
* meta-llama/Llama-2-7b-chat-hf (orange and dark blue)

![image](https://github.com/user-attachments/assets/39eca784-edf3-441b-a83f-bc53c3ac8058)

## Merge criteria:
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2024-08-14 10:49 UTC, Bobbins228 requested changes
Just some nits for the Cluster Configuration parameters that are being depreciated. - The notebook should be updated with these params as well :) 

I am going to try and test this today

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        min_cpus=8,
```suggestion
        worker_cpu_requests=8,
```

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        max_cpus=16,
```suggestion
        worker_cpu_limits=16,
```

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        min_memory=32,
```suggestion
        worker_memory_requests=32,
```

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        max_memory=64,
```suggestion
        worker_memory_limits=64,
```

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        head_gpus=1,
```suggestion
        head_extended_resource_requests={"nvidia.com/gpu": 1},
```

2024-08-14 10:49 UTC, Bobbins228 commented on examples/ray-finetune-llm-deepspeed/README.md
> +        num_gpus=1,
```suggestion
        worker_extended_resource_requests={"nvidia.com/gpu": 1},
```

2024-08-14 16:12 UTC, astefanutti commented
> Just some nits for the Cluster Configuration parameters that are being depreciated. - The notebook should be updated with these params as well :)
> 
> I am going to try and test this today

Would you know the timeline when these new fields got introduced? If they'll all be available in the upcoming RHOAI 2.12 release, I guess we can make upgrading to that version a prerequisite.

2024-08-15 09:29 UTC, Bobbins228 commented
@astefanutti These fields are introduced as of SDK v0.18.0.

2024-08-15 15:11 UTC, ChristianZaccaria commented on examples/ray-finetune-llm-deepspeed/README.md
> +        "--eval-batch-size-per-device=8 "
For my own knowledge: Is there a 'rule-of-thumb' to follow for these values in relation to the number of devices that are available? Or is it a case of trial and error based on how it is performing?

2024-08-15 15:35 UTC, ChristianZaccaria commented
> @astefanutti These fields are introduced as of SDK v0.18.0.

Correct ^, that was 3 weeks ago. However, I discovered just now that the `odh-notebooks-sync` workflow hasn't been working for around 2 months, the latest SDK available in RHOAI notebook images is v0.16.0, hence the new parameters will probably not be included for 2.12.
https://github.com/project-codeflare/codeflare-sdk/actions/workflows/odh-notebooks-sync.yml

2024-08-19 11:45 UTC, astefanutti commented on examples/ray-finetune-llm-deepspeed/README.md
> +        "--eval-batch-size-per-device=8 "
Deepspeed has many configuration parameters that affects how much memory is required w.r.t. the number of devices. It provides some tools to estimate the memory requirements depending on the configuration: https://deepspeed.readthedocs.io/en/latest/memory.html. Beyond, those estimates, that remains mostly empirical.

2024-08-19 11:52 UTC, ChristianZaccaria commented on examples/ray-finetune-llm-deepspeed/README.md
> +        "--eval-batch-size-per-device=8 "
Thanks!! - That's super helpful

2024-08-19 11:57 UTC, ChristianZaccaria commented
I'm checking with Harshad for which rhoai release will the new SDK (0.19.1) be available. In any case, you're right, we are still using i.e., `num_gpus` in our notebooks. I think we can keep it as such until we update everything.

2024-08-26 10:41 UTC, astefanutti commented
@Bobbins228 I've updated it to use the latest SDK version (and rebased on top of what @Ygnas had already updated). Could you please take a look?

2024-08-26 10:42 UTC, astefanutti commented
@sutaakar @abhijeet-dhumal is it OK to merge this or there is anything that requires to be adjusted from the testing side?

2024-08-26 11:14 UTC, sutaakar commented
It looks fine to me, though I didn't run it by myself.
Can be verified as part of test coverage done by Abhijeet.

2024-08-26 11:26 UTC, Bobbins228 commented
@astefanutti /lgtm 
I can verify it myself on top of Abhijeets test coverage

2024-08-26 12:04 UTC, Bobbins228 commented
I was unsuccessful in gathering GPU instances. Spoke with Abhijeet and he is currently testing the new example, he will drop an update here when finished.

2024-08-26 16:02 UTC, abhijeet-dhumal commented
@astefanutti @Bobbins228 
I ran test by rebasing [my test-PR](https://github.com/opendatahub-io/distributed-workloads/pull/197/commits/304c810496466fdef417310addc84ede53fad52d) with this PR using `zero_3_offload_optim+param.json` and did some changes in [input params](https://github.com/opendatahub-io/distributed-workloads/pull/197/commits/304c810496466fdef417310addc84ede53fad52d#diff-518bd56270f4732788268a6aeb8f934c77f8d4436ae0aa2961e434bc54be1cd0R60) but it raises below error each time after 7 mins during  rayJobExecution : 
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.81 GiB. GPU
```
[ray-job-log-raysubmit_r7HQfNmc1K1RTw4E.log](https://github.com/user-attachments/files/16750933/ray-job-log-raysubmit_r7HQfNmc1K1RTw4E.log)

but when I ran same test using `zero_3_llama_2_7b.json`, it works seamlessly .. 
It seems there are no changes required in this PR from testing perspective ! :rocket:

2024-08-26 16:09 UTC, astefanutti commented
@abhijeet-dhumal Llama 3.1 8B has more parameters than Llama 2 7B so it requires more memory. You can try lowering the batch size using the `batch-size-per-device` option, otherwise you can explicitly set the pre-trained model to Llama 2 7B which should restore your previous configuration.

2024-08-27 07:37 UTC, abhijeet-dhumal commented
Added test for Llama 3.1 8B :  https://github.com/opendatahub-io/distributed-workloads/pull/197/files#diff-518bd56270f4732788268a6aeb8f934c77f8d4436ae0aa2961e434bc54be1cd0R35

Test-Configuration : 
1. 1x g5.8xlarge gpu
2. ModelConfig : zero_3_llama_2_7b.json / zero_3_offload_optim_param.json
3. head_cpus=2
4. num_workers=1
5. head_memory=48
6. batch-size-per-device = 6
7. worker_memory_requests=64
8. worker_memory_limits=128

![image (124)](https://github.com/user-attachments/assets/84daa581-0268-4cd7-ad2e-e23b1e7ef33a)

2024-08-27 08:50 UTC, astefanutti commented
@abhijeet-dhumal I've renamed the file so it doesn't have the problematic character. PTAL.

2024-08-27 09:48 UTC, abhijeet-dhumal commented
/lgtm

2024-08-27 10:05 UTC, sutaakar approved these changes

2024-08-27 10:08 UTC, merged