Add testing template
opendatahub-io/distributed-workloads pull request #21
Opened 2023-03-28 19:17 UTC by MichaelClifford

This PR adds a testing template we can use to build our e2e tests for the distributed workloads/CodeFlare Stack.

* The template includes an empty function for each of the test issues we outlined on our [issues](https://github.com/opendatahub-io/distributed-workloads/issues) page. But feel free to supplement with more supporting functions if needed. 

* I added a small subset of tests for the KubeRay operator to get us started and provide an example of how to write tests in this format. 

* There is also a `resources` directory where we can add whatever scripts, yaml files, etc we will need during testing. It is currently just populated with template python file.

2023-03-28 19:20 UTC, Maxusmusti requested changes
Some very minor nits, once fixed it LGTM

2023-03-28 19:20 UTC, Maxusmusti commented on tests/basictests/distributed-workloads.sh
> +os::test::junit::declare_suite_end
missing newline at EOF

2023-03-28 19:20 UTC, Maxusmusti commented on tests/resources/test_mcad_ray.py
> +    pass
missing newline at EOF

2023-03-28 19:20 UTC, Maxusmusti commented on tests/basictests/distributed-workloads.sh
> +function install_distributred_workloads_kfdef(){
distributred -> distributed

2023-03-28 19:21 UTC, anishasthana requested changes

2023-03-28 19:21 UTC, anishasthana commented on tests/basictests/distributed-workloads.sh
> +    haeder: "Installing Codeflare Operator"
```suggestion
    header: "Installing CodeFlare Operator"
```

2023-03-28 19:24 UTC, MichaelClifford commented
:upside_down_face: Sorry for the spelling errors. Should be fixed now.

2023-03-28 19:35 UTC, Maxusmusti approved these changes
LGTM

2023-03-28 20:31 UTC, tedhtchang commented
which function will test the Notebook ?

2023-03-28 21:01 UTC, MichaelClifford commented
We might need an additional tests for the notebook image itself.  However, I'm assuming it will be part of both `tests_mcad_ray_functionality()` and `tests_mcad_torchx_functionality()` as those will run the SDK from the notebook image.

2023-03-29 20:10 UTC, KPostOffice reviewed
This looks good to me. Not blocking, just a question.

2023-03-29 20:10 UTC, KPostOffice commented on tests/basictests/distributed-workloads.sh
> +source $TEST_DIR/common
Do you know where this actually comes from? Is this included in the image or something. I saw it in the odh-manifests too. I assume it provides the functions used for testing like `os::cmd::expect_success`

2023-03-29 20:32 UTC, MichaelClifford commented on tests/basictests/distributed-workloads.sh
> +source $TEST_DIR/common
I think you are right, @KPostOffice. you can see more about the testing framework here: https://github.com/opendatahub-io/odh-manifests/blob/master/tests/TESTING.md

2023-03-30 19:20 UTC, KPostOffice commented on tests/basictests/distributed-workloads.sh
> +install_distributred_workloads_kfdef
```suggestion
install_distributed_workloads_kfdef
```

2023-03-31 15:58 UTC, MichaelClifford commented
@anishasthana @KPostOffice @tedhtchang @Maxusmusti 
I added a test README along with util file needed for testing and simplified the example tests. 

Please take another look and let me know if its good to go :smile:

2023-03-31 18:33 UTC, jbusche commented
LGTM, thanks Michael!

2023-03-31 20:15 UTC, anishasthana approved these changes

2023-03-31 20:15 UTC, merged