CodeFlare Installation test
opendatahub-io/distributed-workloads pull request #22
Opened 2023-03-30 19:20 UTC by KPostOffice

## Description

## How Has This Been Tested?
Will run tests on my local machine

## Merge criteria:
Depends on #21 

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-03-31 21:17 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +install_distributred_workloads_kfdef
```suggestion
install_distributed_workloads_kfdef
```

2023-03-31 21:18 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    header: "Installing distributed workloads kfdef"
```suggestion
    header "Installing distributed workloads kfdef"
```

2023-03-31 22:32 UTC, tedhtchang commented
Tested using the following command
```
git clone https://github.com/opendatahub-io/peak
cd peak/
git submodule update --init
echo distributed-workloads nil https://github.com/KPostOffice/distributed-workloads 15-v1 > my-distributed-workloads
chmod +x operator-tests/distributed-workloads/tests/basictests/distributed-workloads.sh
./run.sh distributed-workloads
```

2023-03-31 22:34 UTC, tedhtchang requested changes

2023-03-31 22:34 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc apply -f ../distributed-workloads-kfdef.yaml"
Where is this `distributed-workloads-kfdef.yaml` ? did you mean?
```suggestion
    os::cmd::expect_success "oc apply -f $RESOURCEDIR/../../codeflare-stack-kfdef.yaml"
```

2023-03-31 22:34 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    header: "Testing MCAD TorchX Functionality"
```suggestion
    header "Testing MCAD TorchX Functionality" 
```

2023-03-31 22:34 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    header: "Testing MCAD Ray Functionality"
```suggestion
    header "Testing MCAD Ray Functionality"
```

2023-03-31 22:34 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    header: "Uninstalling distributed workloads kfdef"
```suggestion
    header "Uninstalling distributed workloads kfdef"
```

2023-03-31 22:34 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    header: "Uninstalling Codeflare Operator"
```suggestion
    header "Uninstalling Codeflare Operator"
```

2023-04-03 18:57 UTC, jbusche approved these changes
Hi Kevin,
I just tried it and it looks good to me... CodeFlare Operator is installed as expected.

2023-04-03 18:58 UTC, jbusche commented
Looked like a good result to me:
```
./run.sh
++++++ /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/ray/tests/basictests
Now using project "basictests-bafq" on server "https://api.jimbig412.cp.fyre.ibm.com:6443".

++++ /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/ray/tests/basictests/ray.sh
./run.sh: line 124: /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/ray/tests/basictests/ray.sh: Permission denied
failed: /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/ray/tests/basictests/ray.sh
++++++ /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/tests/basictests
Already on project "basictests-bafq" on server "https://api.jimbig412.cp.fyre.ibm.com:6443".

++++ /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh

Running example test

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:15: executing 'oc project opendatahub' expecting success...


✔ SUCCESS after 0.122s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:15: executing 'oc project opendatahub' expecting success

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:16: executing 'oc get pods' expecting success...


✔ SUCCESS after 0.109s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:16: executing 'oc get pods' expecting success


Installing Codeflare Operator

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:21: executing 'oc apply -f /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/tests/basictests/../resources/codeflare-subscription.yaml' expecting success...


✔ SUCCESS after 2.786s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:21: executing 'oc apply -f /root/KEVIN/peak/operator-tests/opendatahub-kubeflow/tests/basictests/../resources/codeflare-subscription.yaml' expecting success

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:24: executing 'oc get pods -n openshift-operators | grep codeflare-operator-controller-manager | awk '{print $2}'' expecting any result and text '2/2'; re-trying every 10s until completion or 1200.000s...


✔ SUCCESS after 0.122s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:24: executing 'oc get pods -n openshift-operators | grep codeflare-operator-controller-manager | awk '{print $2}'' expecting any result and text '2/2'; re-trying every 10s until completion or 1200.000s

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:27: executing 'oc get crd instascales.codeflare.codeflare.dev  | wc -l' expecting success and text '2'...


✔ SUCCESS after 0.125s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:27: executing 'oc get crd instascales.codeflare.codeflare.dev  | wc -l' expecting success and text '2'

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:28: executing 'oc get crd mcads.codeflare.codeflare.dev | wc -l' expecting success and text '2'...


✔ SUCCESS after 0.090s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:28: executing 'oc get crd mcads.codeflare.codeflare.dev | wc -l' expecting success and text '2'

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:29: executing 'oc get crd appwrappers.mcad.ibm.com | wc -l' expecting success and text '2'...


✔ SUCCESS after 0.114s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:29: executing 'oc get crd appwrappers.mcad.ibm.com | wc -l' expecting success and text '2'

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:30: executing 'oc get crd queuejobs.mcad.ibm.com | wc -l' expecting success and text '2'...


✔ SUCCESS after 0.111s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:30: executing 'oc get crd queuejobs.mcad.ibm.com | wc -l' expecting success and text '2'

Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:31: executing 'oc get crd schedulingspecs.mcad.ibm.com | wc -l' expecting success and text '2'...


✔ SUCCESS after 0.125s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:31: executing 'oc get crd schedulingspecs.mcad.ibm.com | wc -l' expecting success and text '2'


Installing distributed workloads kfdef


Testing MCAD TorchX Functionality


Testing MCAD Ray Functionality


Uninstalling distributed workloads kfdef


Uninstalling Codeflare Operator

Already on project "opendatahub" on server "https://api.jimbig412.cp.fyre.ibm.com:6443".
One or more tests failed:

	/root/KEVIN/peak/operator-tests/opendatahub-kubeflow/ray/tests/basictests/ray.sh

./run.sh took 5 seconds
[INFO] Exiting with 1
```
and
```
oc get pods -n openshift-operators
NAME                                                    READY   STATUS    RESTARTS   AGE
codeflare-operator-controller-manager-6579fb6c5-4b97p   2/2     Running   0          53s
opendatahub-operator-66dd4b8fbc-tzjm6                   1/1     Running   0          24m
```

2023-04-03 21:06 UTC, KPostOffice commented
@jbusche Do you have write access to approve this?

2023-04-03 21:19 UTC, jbusche approved these changes
lgtm

2023-04-03 21:23 UTC, jbusche commented
Hi @KPostOffice, no - just tried approving again, and it's not seeming to allow my approve.  I MIGHT have merge capability once the approval is done, but I suspect not.

2023-04-04 15:40 UTC, MichaelClifford approved these changes

2023-04-04 15:40 UTC, merged