Adding Mini ML Workloads + TorchX-MCAD Test
opendatahub-io/distributed-workloads pull request #31
Opened 2023-04-06 18:15 UTC by Maxusmusti

Adding a mini-mnist workload to the Ray test, as well as an identical test via torchx-mcad through the SDK as well.

2023-04-06 20:55 UTC, MichaelClifford commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc create configmap notebooks --from-file=${RESOURCEDIR}/mnist_ray_mini.ipynb"
can we give this config map a more descriptive name? like mcad-ray-test-notebook?

2023-04-06 20:55 UTC, MichaelClifford commented on tests/basictests/distributed-workloads.sh
>      os::cmd::expect_success "cat ${RESOURCEDIR}/custom-nb-small.yaml | sed s/%INGRESS%/$(oc get ingresses.config/cluster -o jsonpath={.spec.domain})/g |sed s/OCPSERVER/$(oc whoami --show-server=true|
Nit: But for readability, you could break this up into a few steps, getting the ocp info, updating the yaml and then applying it.

2023-04-06 20:58 UTC, MichaelClifford commented on tests/basictests/distributed-workloads.sh
>      # Wait for the mnisttest appwrapper state to become running
We should also take the resources down and check to confirm they've been deleted.

2023-04-07 22:32 UTC, tedhtchang approved these changes
/lgtm I passed all the tests in the test_mcad_torchx_functionality() on my environment.
UPDATED: and passed the other tests too.

2023-04-10 17:48 UTC, MichaelClifford requested changes

2023-04-10 17:48 UTC, MichaelClifford commented on tests/basictests/distributed-workloads.sh
> +
Do we want a check here that tells us the clusters and the app wrappers have been deleted by SDK calls in the notebook?

2023-04-12 19:01 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
@jbusche found that the pvc can carry over some junk file over so we should delete the pvc.
```suggestion
    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
    os::cmd::expect_success "oc delete pvc jupyterhub-nb-kube-3aadmin-pvc -n ${ODHPROJECT} || true"
```

2023-04-12 19:04 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
```suggestion
    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
    os::cmd::expect_success "oc delete pvc jupyterhub-nb-kube-3aadmin-pvc -n ${ODHPROJECT} || true"
```

2023-04-12 19:07 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete cm notebooks-mcad -n ${ODHPROJECT} || true"
No need to be in form of `os::cmd....` but they do require the `||  true`. Otherwise, the test maybe interrupted when oc delete an non exiting resource.

2023-04-12 19:40 UTC, jbusche commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
Ah, I put that in my PR [34](https://github.com/opendatahub-io/distributed-workloads/pull/34) already Ted...  but whichever, I can remove if needed too.

2023-04-13 18:55 UTC, tedhtchang commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete notebook jupyter-nb-kube-3aadmin -n ${ODHPROJECT} || true"
Maybe better to keep both. This suggestion is for pre test clean up as you know the pvc may be created from the `test_mcad_torchx_functionality` test which runs before this test.

2023-04-13 20:51 UTC, MichaelClifford approved these changes

2023-04-13 20:52 UTC, merged