add Containerfile for mcad mnist test
opendatahub-io/distributed-workloads pull request #32
Opened 2023-04-10 19:42 UTC by MichaelClifford

Added Containerfile used to build image for testing MCAD job submission functionality. 

Depends on `mnist.py` in #31

2023-04-10 19:43 UTC, MichaelClifford commented
cc @jbusche

2023-04-11 01:10 UTC, jbusche commented
Well, shoot @MichaelClifford - this has been tough on two fronts - one is the base torchx image is so big, and the other is apparently I can't built it properly - no matter what Dockerfile I use, when I try to utilize it I get `Environment variable 'TORCHELASTIC_ENABLE_FILE_TIMER' not found. Do not start FileTimerServer.` 

I suspect there's some trick to building the image with the right env items.

My image, if I could succeed in running it, WOULD potentially be better though - it closes two compliance issues and seven vulnerabilities.  (It doesn't improve anything if I use the latest torchx 0.6.0dev0 build)
```
Before: 
 |  | complianceFailureSummary | C:0/H:2/M:0/L:0/T:2
 |  | vulnerabilityFailureSummary | C:3/H:11/M:9/L:1/T:24
After:
 |  | complianceFailureSummary | C:0/H:0/M:0/L:0/T:0
 |  | vulnerabilityFailureSummary | C:3/H:10/M:3/L:1/T:17
 ```

2023-04-11 01:12 UTC, jbusche requested changes
Hey Michael, I'm thinking these might be helpful changes, but I need to learn the right way to build this so it runs properly.
```
FROM ghcr.io/pytorch/torchx:0.5.0

ADD mnist.py /app/mnist.py

# Add non-root user for container
RUN groupadd --system --gid=9999 torchx && \
    useradd --system --create-home --uid=9999 --gid=torchx torchx

# change group permissions for running in OCP
RUN chown -R torchx /app
RUN chgrp -R torchx /app
RUN chmod -R g+w /app # Note, this might not be needed since torchx above has write permission already

# Upgrade the OS
RUN apt-get update
RUN apt-get upgrade -y

# Remove private keys stored in image
RUN find /opt/conda -name "*.pem" -delete
RUN find /opt/conda/pkgs -name "*.asc" -delete

# Change to non-root torchx user
USER torchx

ENTRYPOINT ["python", "/app/mnist.py"]
```

2023-04-11 14:19 UTC, MichaelClifford commented
Thanks @jbusche I'll make these changes and see if I can build it

2023-04-13 18:55 UTC, MichaelClifford commented
@jbusche haven't had a chance to get your image updates to run correctly. Should we move forward with the current containerfile and image for now? Can we merge this PR?

2023-04-13 20:55 UTC, Maxusmusti approved these changes
LGTM

2023-04-13 20:56 UTC, merged