uninstall_codeflare_operator function has problem with pod deletion test
opendatahub-io/distributed-workloads pull request #34
Opened 2023-04-12 00:26 UTC by jbusche

## Description
Unfortunately, I think due to the latest update of the ODH operator, the current check to ensure that the CodeFlare ] operator pod has been deleted is also catching the ODH operator and therefore the function never completes.

The change below, instead of checking for the CodeFlare Operator pod, it just checks now for the CodeFlare deployment, making sure that that has been removed before continuing.

## How Has This Been Tested?
Using the peak e2e method, I've been running the uninstall_codeflare_operator function and it's properly completing now:
```
./run.sh distributed-workloads.sh
...
Uninstalling Codeflare Operator
...
Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:176: executing 'oc get deploy codeflare-operator-controller-manager -n openshift-operators' expecting any result and text '*NotFound*'; re-trying every 10s until completion or 1200.000s...

✔ SUCCESS after 0.162s: operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:176: executing 'oc get deploy codeflare-operator-controller-manager -n openshift-operators' expecting any result and text '*NotFound*'; re-trying every 10s until completion or 1200.000s
```

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-04-12 19:20 UTC, jbusche commented
Just added pvc deletion after the notebook and imagestream are cleaned up.

2023-04-13 18:56 UTC, MichaelClifford approved these changes
LGTM

2023-04-13 21:00 UTC, Maxusmusti requested changes

2023-04-13 21:00 UTC, Maxusmusti commented on tests/basictests/distributed-workloads.sh
> +    os::cmd::expect_success "oc delete pvc jupyterhub-nb-kube-3aadmin-pvc -n ${ODHPROJECT} || true"
```suggestion
```

2023-04-13 21:03 UTC, Maxusmusti approved these changes
LOOKS GOOD TO ME

2023-04-13 21:04 UTC, merged