Add GitHub Action for automatic release
opendatahub-io/distributed-workloads pull request #61
Opened 2023-06-29 08:23 UTC by jiripetrlik

2023-07-06 00:20 UTC, tedhtchang requested changes
I believe this fixes #61.
I tried to image the intended use of this workflow please correct me if wrong. I triggered it manually from my own fork like so:
![image](https://github.com/opendatahub-io/distributed-workloads/assets/7155778/99b1261a-b752-465c-9810-16e0f753e1fb)
I get an updated [README.md](https://github.com/tedhtchang/distributed-workloads#compatibilty-matrix) in the main of my fork:
<img width="382" alt="image" src="https://github.com/opendatahub-io/distributed-workloads/assets/7155778/1e95478e-ec08-45ea-a61a-f37f37116ec7">
and a new tag:
<img width="454" alt="image" src="https://github.com/opendatahub-io/distributed-workloads/assets/7155778/f1a3a10c-e7a2-44d4-82d2-616b34d6a61f">

2023-07-06 00:20 UTC, tedhtchang commented on .github/workflows/release.yaml
> +              run: sed -i "s/\(| CodeFlare-SDK[ ]*\)|.*|/\1| ${{ github.event.inputs.codeflare-sdk-version }} |/" README.md
Missing InstaScale substation 
```suggestion
              run: sed -i "s/\(| CodeFlare-SDK[ ]*\)|.*|/\1| ${{ github.event.inputs.codeflare-sdk-version }} |/" README.md
           - name: Change InstaScale version in README
              run: sed -i "s/\(| InstaScale[ ]*\)|.*|/\1| ${{ github.event.inputs.instascale-version }} |/" README.md
```

2023-07-06 01:10 UTC, tedhtchang reviewed
Another idea is using yq command:
![image](https://github.com/opendatahub-io/distributed-workloads/assets/7155778/bb66576f-1b03-4552-af36-85dd26f863d4)

2023-07-06 01:10 UTC, tedhtchang commented on .github/workflows/release.yaml
> +                value: "codeflare-operator.${{ github.event.inputs.codeflare-operator-version }}"
A second thought is using `yq` command:
```suggestion
            - name: Update codeflare-operator version in tests/resources/codeflare-subscription.yaml file
              run: |
                yq -i '.spec.startingCSV = "codeflare-operator.${{github.event.inputs.codeflare-operator-version}}"' tests/resources/codeflare-subscription.yaml
```

2023-08-03 19:57 UTC, anishasthana commented
@jiripetrlik have you had a chance to look at this again?

2024-06-19 07:55 UTC, sutaakar commented
Not relevant any more, closing.

2024-06-19 07:55 UTC, closed without merging