Update file paths in Quick-Start
opendatahub-io/distributed-workloads pull request #82
Opened 2023-08-15 09:50 UTC by ChristianZaccaria

Closes #81 

## Description

- Updated file paths to the guided demos based on changes made on this [PR and comment](https://github.com/project-codeflare/codeflare-sdk/pull/296#issuecomment-1673743770). 
- Updated dead links.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-08-16 15:15 UTC, Bobbins228 requested changes
I think it might be a good idea to update the following [run the demo notebook](https://github.com/opendatahub-io/distributed-workloads/blob/4c38996e824b7db091738be1b3c14006e4a1360d/Quick-Start.md#run-the-demo-notebook) tutorial to reflect the notebook you reference `codeflare-sdk/demo-notebooks/guided-demos/2_basic_jobs.ipynb` because right now the tutorial does not match what is written in that particular notebook which could cause confusion.

2023-08-16 17:32 UTC, ChristianZaccaria commented
> I think it might be a good idea to update the following [run the demo notebook](https://github.com/opendatahub-io/distributed-workloads/blob/4c38996e824b7db091738be1b3c14006e4a1360d/Quick-Start.md#run-the-demo-notebook) tutorial to reflect the notebook you reference `codeflare-sdk/demo-notebooks/guided-demos/2_basic_jobs.ipynb` because right now the tutorial does not match what is written in that particular notebook which could cause confusion.

@Bobbins228 You're absolutely right, thank you. Hopefully the changes now make sense. I modified the tutorial to closely match what is in the notebook. Let me know what you think :)

2023-08-17 09:03 UTC, Bobbins228 requested changes
Looks good fits more into what that demo notebook looks like just one minor nitpick

2023-08-17 09:03 UTC, Bobbins228 commented on Quick-Start.md
> +    instascale=False,
```suggestion
    instascale=False,
    machine_types = ["m4.xlarge", "g4dn.xlarge"]
```
For the sake of making things easier for the reader we should group these two together. 
It's alright to have `machine_types = ["m4.xlarge", "g4dn.xlarge"]` without a comment because the SDK will ignore it if `InstaScale=False`

I know `machine_types` is not in that notebook but it is still important for people to know what InstaScale requires in case it is set to True.

2023-08-17 09:03 UTC, Bobbins228 commented on Quick-Start.md
> +    # machine_types = ["m4.xlarge", "g4dn.xlarge"]
Remove this line

2023-08-17 09:43 UTC, Bobbins228 commented
/lgtm

2023-08-17 09:43 UTC, Bobbins228 approved these changes
/lgtm

2023-08-30 08:55 UTC, goern commented
is there any issue not merging this PR?

2023-08-30 10:33 UTC, ChristianZaccaria commented
> is there any issue not merging this PR?

Currently waiting on `owners` approval for merge. @dimakis This should be good to go if you're okay with :+1:

2023-08-30 11:52 UTC, ChristianZaccaria commented
/retest

2023-08-30 17:55 UTC, MichaelClifford requested changes

2023-08-30 17:55 UTC, MichaelClifford commented on Quick-Start.md
> +    # machine_types = ["m4.xlarge", "g4dn.xlarge"]
can you take out this line?

2023-08-30 17:55 UTC, MichaelClifford commented on Quick-Start.md
> +    script="mnist.py",
Can you add a comment above with a link to the "mnist.py" file. Otherwise I think its a little unclear to the user where this is coming from and will cause their runthrough to fail.

2023-08-30 17:55 UTC, MichaelClifford commented on Quick-Start.md
> +cluster.cluster_dashboard_uri()
can you put these in 3 different python formatted boxes? I think if you run them all in a single cell like shown here only the logs will print.

2023-08-31 11:38 UTC, ChristianZaccaria commented on Quick-Start.md
> +    # machine_types = ["m4.xlarge", "g4dn.xlarge"]
I thought I had removed it, great catch thanks! :+1:

2023-08-31 11:39 UTC, ChristianZaccaria commented on Quick-Start.md
> +    script="mnist.py",
I added the comment above, let me know if it meets with expectations.

2023-08-31 11:40 UTC, ChristianZaccaria commented on Quick-Start.md
> +cluster.cluster_dashboard_uri()
Tested that just now, you are absolutely correct! I changed that just now thank you! :+1:

2023-09-05 14:02 UTC, MichaelClifford approved these changes
lgtm

2023-09-05 14:46 UTC, merged